### ISSUE TITLE
Too Long For my Screen

### ISSUE THREAD

**Issue by LemonBoomarang81** [LucasOe/Rainmeter#2]
The bar, amazing creation, by the way, extends onto my second screen and I do not know how to make it fit within my main screen.

**Comment by LucasOe** [comment]
Because I use a 1440p monitor the default settings are set to this size. You can change the position in `Documents/Rainmeter/Skins/LucasOe/@Resources/settings.inc`. You will find different values ending with "place" there which adjust the position of the widgets for the bar skin. Lower some of the bigger values until everything is visible. In the Document you can also hide widgets you don't want to see.

I'll try to update the skin so it works out of the box for every screen size in the future. Right now you have to adjust the values for your screen size manually.
